src/app/shared/footer/footer.component.html
To be aligned with the page, no?
=> Move left to right socials logos in footer

src/app/explorer/farmer/farmer.component.html
Minor changes on farmer dashboard
---
Before:
After:
Changes:
=> Minor changes farmer dashboard

src/assets/scss/custom/_separator.scss
=> Remove small green line

src/assets/scss/custom/_variables.scss
* Related with issue #9
* Increase max-width from 1040px to 1200px by default (xl size)
Before:
After:
=> Increase max-width from 1040 to 1200 px

src/app/explorer/farmer/farmer.component.html
Fix charts size after tabs changes (issue #11).
=> Fix farmer charts (issue #11)

src/app/shared/footer/footer.component.html, src/app/shared/navbar/navbar.component.html
* Add Twitter logo/link in navbar
* Fix Twitter title in footer
=> Fix and update twitter

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/dashboard/dashboard.component.ts
Add XCH price (USD) in the explorer dashboard:
Reference with issue #12
=> Add XCH price in explorer dashboard

src/app/explorer/explorer.component.html, src/app/faq/faq.component.html, src/app/fees/fees.component.html, src/app/join/join.component.html, src/app/landing/landing.component.html, src/app/partners/partners.component.html, src/app/terms/terms.component.html, src/assets/scss/argon.scss, src/assets/scss/custom/_animations.scss
* Move round background on all pages (css)
It's not very important ^^"
No
=> Improve default design, move round

src/app/faq/faq.component.html
* Improve FAQ page with "How to set name in explorer? (alias)"
=> Add 'How to set name in explorer' in the FAQ page

src/app/explorer/farmer/farmer.component.html
Improve farmer failed partials filter
* Add reason details for each error
* Improve design with more space
=> Improve farmer failed partials filter

src/app/explorer/farmer/farmer.component.html
* Add harvesters count
* Add partials performance
=> Improve farmer dashboard

src/app/explorer/dashboard/dashboard.component.html
* Add leaderboard (top 3 of farmers)
=> Improve dashboard with farmers leaderboard (issue #23)

src/app/explorer/dashboard/dashboard.component.html, src/assets/scss/custom/_global.scss
=> Improve leaderboard

src/app/explorer/farmer/farmer.component.html
* Add "joined at" in farmer details
User arrived before function
User arrived after function
=> Add joined at in farmer details

src/app/explorer/farmer/farmer.component.html
* Add SINGLETON_NOT_POOL partial error details (issue #44)
* Quick fix on partial count
No
=> Add SINGLETON_NOT_POOL partial error (issue #44)

src/app/explorer/dashboard/dashboard.component.html
* Change between points and difficulty
No
=> Change between points <-> difficulty

src/app/explorer/farmer/farmer.component.html
* Activate failed partials option from checkbox and text (issue #52)
No
=> Improve failed partials option (issue #52) and remove empty lines

src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts
In farmer page and payout tab:
* Add columns name in CSV
* Rename from "Transaction Block" to "Transaction"
* Add "payout" field with payout reference (link)
=> Improve CSV export

src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts
* Remove legend on partials charts (basic colors, green=success and red=error)
* Rename AxisLabel (I work on payout chart)
=> Remove legend and rename axislabels

src/app/explorer/farmer/farmer.component.html
Improve giveway farmer with link :)
=> Improve giveway winner name with link

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/farmer/farmer.component.html
@william-gr to confirm if it's good for you
=> Replace from confirmed_block_index to farmed_height block

src/app/giveaway/giveaway.component.html
=> Improve giveaway page

src/app/data.service.ts, src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/dashboard/dashboard.component.ts
* Add payouts pagination on dashboard
Farmer page (payouts tab) is not affected by this change
=> Add payouts pagination

src/app/landing/landing.component.ts
* Improve format of date on the pool space chart
=> Improve date format on pool space chart

src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts, src/assets/scss/bootstrap/_modal.scss, src/assets/scss/bootstrap/_variables.scss, src/assets/scss/custom/_global.scss, src/assets/scss/custom/_variables.scss
* Display all partial error in a popup
=> Improve partial error details

src/app/landing/landing.component.html
* Improve djerfy in landing page
=> Improve djerfy in landing page

src/app/explorer/dashboard/dashboard.component.html
* Add Pool Space when the block has been won
=> Add pool space when the block has been won

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/login/login.component.html
* Change `maxLength` from 15 to 16
Before:
After:
=> Fix launcher name with emoji

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts, src/app/explorer/payout/payout.component.html
* Farmer estimated reward in XCH and USD (based from the current price)
=> Farmer estimated reward

src/app/explorer/dashboard/dashboard.component.html
* Automatically use "hour(s)" or "day(s)" for ETW (in day if more than 24h)
=> Improve ETW value with hours or days if more than 24h

src/app/app.module.ts, src/app/app.routing.ts, src/app/calculator/calculator.component.html, src/app/calculator/calculator.component.ts, src/app/shared/footer/footer.component.html, src/app/shared/navbar/navbar.component.html
* Add profit calculator component (v1)
* Based on XCH/TiB/day and the current XCH price (USD)
* Blog menu has been removed (useless)
* FAQ menu has been moved in the footer
* Calculator menu has been added in navbar
=> Profit calculator

src/app/explorer/farmer/farmer.component.html
* Split estimated reward per day and per month
=> Split estimated reward per day and per month

src/app/calculator/calculator.component.css, src/app/calculator/calculator.component.html
On calculator page:
* Add text input, linked with range input
* Green range bar
* Minor fixes
=> Improve calculator page

src/app/calculator/calculator.component.html, src/app/calculator/calculator.component.ts
* Add estimated utilization space in the pool (with himself)
* #126
=> Add estimated utilization space in the pool

src/app/explorer/dashboard/dashboard.component.css, src/app/explorer/dashboard/dashboard.component.html
* Increase launcher name/id characters (from 20 to 30)
* Move launcher name/id in left
=> Update launcher name/id in left and increase limit of characters

src/app/explorer/dashboard/dashboard.component.html
* Change points to points_pplns in top3
* Left launcherid title
=> Left launcherid title and update points

src/app/data.service.ts, src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/dashboard/dashboard.component.ts
* Add button to show only active farmers (yes by default now)
* Update syntax of ts file
* #101
=> Show filter active farmers

src/app/explorer/dashboard/dashboard.component.html
=> Fix farmer filter on dashboard

src/locale/zh-Hans-CN.xlf
* Improve Chinese translations (file from Discord)
=> Improve Chinese translations

src/app/explorer/farmer/farmer.component.html, src/app/giveaway/giveaway.component.html
* Fix giveaway winner name
* Update giveaway tab
* Issue #139
=> Fix giveaway winner name

src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts
* Add total block(s) won
* Add effort average
* Add pool space when block has been found
None
=> Improve blocks tab on farmer page

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/farmer/farmer.component.html
* Enable enter/return key in farmer search field (issue #144)
* Fix blocks on farmer page (issue #143)
* Improve details for partial error
=> Improvements

src/app/explorer/farmer/farmer.component.css, src/app/explorer/farmer/farmer.component.html
* Update button with OpenChia color
Before:
After:
@william-gr Only if it's good for you (if you prefer or not), else you can close this PR directly ;)
=> Openchia color button

src/app/shared/navbar/navbar.component.html
=> Add extras menu

src/app/landing/landing.component.html, src/app/landing/landing.component.ts, src/app/stats/stats.component.html, src/app/stats/stats.component.ts
* Move pool space chart in stats page (disabled for the moment)
* Move twitter widget
=> Update landing page (twitter widget and chart)

src/app/calculator/calculator.component.html, src/app/fees/fees.component.html, src/app/landing/landing.component.html, src/app/shared/navbar/navbar.component.html, src/assets/scss/custom/_global.scss
=> Improve pages

src/locale/sk.xlf
This pull request contains Slovak translation updates from https://localazy.com/p/openchia/phrases/1186 which cannot be downloaded because of Localazy's free plan limitations and pricing.
@william-gr Please merge. Thanks.
See also: https://github.com/openchia/web/issues/64
=> Update sk translation

src/locale/sk.xlf
=> Revert "Update sk translation"

src/app/stats/stats.component.ts
Remove useless components (old tests for logs)
No changes
=> Remove useless components

src/app/data.service.ts, src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts, src/app/explorer/login/login.component.html, src/app/explorer/login/login.component.ts, src/assets/scully-routes.json
Allow users to set a minimum payout and set a custom difficulty in login page.
CSV also changed to use the sum of values.
=> Minimum Payout and Custom Difficulty

README.md
Readme update (building part)
No
No
=> Update README (building part)

src/locale/sk.xlf
Please merge. Thanks.
- Fix missing string interpolations such as `"{{ reward_blocks }}"`.
- Add a couple of new translations.
=> Fix and update sk translation

docker/caddy/Caddyfile
Fix text files in Caddy configuration
* robots.txt
* security.txt
* sitemap.xml
Yes on localhost (docker)
No
=> Fix text files in Caddy configuration

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/farmer/farmer.component.html
Update filesize with base2 option
=> Update filesize with base:2

src/app/giveaway/giveaway.component.html
=> Change giveaway tiering

angular.json, src/index.html
Fixes Warning: Unable to locate stylesheet: /home/william/scm/oc-web/assets/vendor/font-awesome/css/all.min.css
=> Fix CSS warning

src/app/data.service.ts, src/proxy.conf.json
A lot of errors in the browser console as it conflicts
None
=> Fix conflict of /ws with webpack dev server websocket

src/app/data.service.ts, src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts, src/app/stats/stats.component.html, src/app/stats/stats.component.ts
Use new APIs for historical data.
=> Add pool and farm size

src/app/shared/navbar/navbar.component.html, src/app/shared/navbar/navbar.component.scss
Improve giveaway in navbar
* Remove static white color, now dynamic (for mobile/tablet)
* Improve spacing between icon and text
=> Improve giveaway in navbar

src/app/data.service.ts, src/app/stats/stats.component.html, src/app/stats/stats.component.ts
Add graph for netspace and xch price
=> Add netspace and XCH price stats

src/app/stats/stats.component.ts
use toFixed for XCH Price and fix Y axis for EiB.
=> Small fixes to stats

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/dashboard/dashboard.component.ts
Improve format of ETW (h:m)
From localhost, not from Docker
Issue #220
=> Improve ETW

src/app/explorer/dashboard/dashboard.component.html
=> Add @@Address translation source

src/app/explorer/dashboard/dashboard.component.html
=> Add space in the front of an info circle

src/app/stats/stats.component.ts
Fixed values on axis charts (stats page)
Tested from local.
Issue #229
=> Use fixed values on axis charts (issue #229)

src/app/data.service.ts, src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts
Add harvesters tab/stats
Screenshot from last revision:
=> Add harvesters tab

src/app/explorer/login/login.component.html, src/app/explorer/login/login.component.ts, src/locale/en.xlf
Send notifications on payment and farm size drop.
=> Add notify for payment and size drop

src/app/explorer/login/login.component.css, src/app/explorer/login/login.component.html
Improve login page
- design/css
- ngbtooltip translation
- tabs (and icons)
=> Improve login page

src/app/explorer/dashboard/dashboard.component.html
=> Fix launcher.share_pplns number for progress bar (issue #244)

src/app/shared/navbar/navbar.component.html, src/assets/scss/custom/_variables-common.scss
Improve navbar:
* Increase width for low resolution screens
* Remove Home from menu
From localhost
Issue #247
=> Improve navbar

src/app/data.service.ts, src/app/explorer/dashboard/term/term.component.html, src/app/explorer/dashboard/term/term.component.ts
Checkboxes to filter too verbose stuff.
=> Allow filtering logs

src/app/fees/fees.component.html, src/app/join/join.component.html, src/app/partners/partners.component.html, src/app/stats/stats.component.html
Fix accordion blocks space
From localhost only
See issue #253 
Issue #253
=> Fix accordion blocks space

src/app/explorer/farmer/farmer.component.html, src/app/fees/fees.component.html
=> Add fee discount

src/app/explorer/farmer/farmer.component.html
=> Be more clear on fees table and add last joined date

package-lock.json
Update package-lock.json, via npm audit fix
No screenshot
Issue #263
=> Update package-lock.json via npm audit fix

src/app/shared/navbar/navbar.component.html, src/index.html
Upgrade font-awesome from 5.15.3 to 6.1.0
Fix moon icon size
Remove "download" icon on "Join our pool" button
From localhost, different pages, light/dark mode, ...
No screenshot
Issue #269
=> Upgrade font-awesome and minor fixes

src/app/explorer/farmer/farmer.component.html
=> Translations: Fix missing space between Estimated_Size and info-circle

src/app/fees/fees.component.html
Please review and merge. Thanks.
=> Add space between the text and the next <h3> element

src/app/giveaway/giveaway.component.html, src/app/shared/footer/footer.component.html, src/app/shared/navbar/navbar.component.html
=> Stop giveaway

src/app/shared/navbar/navbar.component.html
Add dust storm title for mobile
Improve i18n for dark mode
From localhost
No
=> Add dust storm title and improve i18n

src/app/explorer/farmer/farmer.component.html
=> Explanation for partials errors

src/app/fees/fees.component.html
=> Add missing space between sentences

src/app/explorer/farmer/farmer.component.html
Closes #275
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> Add tooltip for ETW and effort

src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts
Summary of rewards with a daily graph.
=> Rewards summary

src/app/fees/fees.component.html
=> Fix grammar on fees page

src/app/explorer/farmer/farmer.component.html, src/app/explorer/farmer/farmer.component.ts
Improve estimated and earned rewards on the farmer page
No screenshot
=> Improve estimated/earned method

src/locale/en.xlf
Please merge. Generated by `"npm run ng xi18n -- --out-file en.xlf"`.
=> Regenerate en.xlf

.github/PULL_REQUEST_TEMPLATE.md, package-lock.json, src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/farmer/farmer.component.html
* Improve rewards in farmer page, with badges
* Improve rewards block in explorer page, with block height and fee
* Improve pull request template
* Upgrade socket.io-parse module (critical severity)
```
socket.io-parser  <4.0.5
Severity: critical
Insufficient validation when decoding a Socket.IO packet - https://github.com/advisories/GHSA-qm95-pgcg-qqfq
fix available via `npm audit fix`
node_modules/socket.io-parser
```
Yes, from localhost
No screenshot
No issue
=> Global improvements

Dockerfile
Upgrade Caddy from v2.6.1 to v2.6.2 (alpine)
No test
No screenshot
No issue
=> Upgrade Caddy to v2.6.2 (alpine)

README.md
Fix pipeline badge in the readme
No test
No screenshot
No issue
=> Fix readme pipeline badge

package-lock.json, package.json
Update modules (security)
* From: `11 vulnerabilities (2 moderate, 9 high)`
* To: `8 vulnerabilities (2 moderate, 6 high)`
From localhost
No screenshot.
No issue.
=> misc: update modules

Dockerfile
Upgrade Caddy from v2.6.2 to v2.6.4 (Alpine based)
No tests.
No screenshot.
No issue.
=> misc: update caddy

src/app/explorer/farmer/farmer.component.ts
When error partials details is opened:
* Fix close buttons
* Enable scroll (because it's long)
Yes, from localhost
No screenshot.
No issue.
=> Fix farmer modal (error partials)

.dockerignore, .gitignore, angular-git-version.js, package-lock.json, package.json, src/app/shared/footer/footer.component.html, src/app/shared/footer/footer.component.ts, src/environments/git-version.ts
Show branch name and the last commit (tooltip) in the footer
Yes from localhost and docker enviromnents
> Here it's `feat/show-git-rev-footer` because stack run on this branch, else it's main of course :)
No issue
=> feat: show git branch/commit in the footer

.github/labels.yml, .github/workflows/github-labels.yml
Improve github issue labels
Github improvement
No screenshot
No issue
=> feat: improve issue labels

src/app/explorer/farmer/farmer.component.css, src/app/explorer/farmer/farmer.component.html, src/app/shared/footer/footer.component.html, src/app/shared/footer/footer.component.ts, src/app/stats/stats.component.html, src/app/stats/stats.component.ts
Global improvements:
* Improve charts (stats page)
* Update earned reward icons (farmer page)
* update download button (farmer page)
* Review github details (footer)
No screenshot
No issue
=> misc: global improvements

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/dashboard/dashboard.component.ts
Add trophy in farmer line for the last block won
No issue
=> feat: add trophy on farmed for the last block won

src/app/stats/stats.component.html, src/app/stats/stats.component.ts
Add pool luck chart in stats page
> Need to rebase after #339 
No issue
=> feat: add pool luck chart in stats page

src/app/explorer/dashboard/dashboard.component.css, src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/farmer/farmer.component.html, src/assets/scss/custom/_badge.scss
Changes:
* Add ngtooltip on effort badges (explorer)
* Configure effort badges in the farmer page (blocks tab)
* Move badge custom css (from explorer to global)
No screenshot
No issue
=> feat: farmer effort badge and improvements

src/app/stats/stats.component.ts
Fix date on blocks luck chart
No screenshot
No issue
=> fix(stats): blocks luck date

.github/dependabot.yml
Configure dependabot
- github-actions dependencies
- npm dependencies
No screenshot
Issue #359
=> feat(github): configure dependabot

.github/workflows/docker.yml, .github/workflows/labels.yml, .github/workflows/npm.yml, .github/workflows/trivy.yml
Review Github-Actions workflows:
* docker
* Remove feat branch (useless)
* Include trivy scan in the base step
* Improve metadata tags
* Build for amd64 (arm64 doesn't works for the moment)
* labels
* From main push or manually (no changes)
* npm
* From pull_request (paths) or manually
* trivy
* From pull_request or manually
No screenshot
Issue #354
=> feat(github): review workflows

src/app/shared/footer/footer.component.html
Fix Github details in footer (conditions)
Yes with a release on localhost
No issue
=> fix: github release match

src/app/explorer/farmer/farmer.component.html
Fix farmer harvester chart
No screenshot
No issue
=> fix: farmer harvesters chart (size)

src/app/stats/stats.component.html, src/app/stats/stats.component.ts
Add pool effort average per day
Issue #349
=> feat(stats): add pool effort average per day

.github/dependabot.yml
=> misc(github): dependabot review

package-lock.json, package.json
Remove `@localazy/cli` module (useless)
Dependabot PR #395
=> misc: remove @localazy/cli module (useless)

Dockerfile, package-lock.json, package.json
Improve node version(s)
* Docker
* Module
Yes from localhost, from cli and docker
no screenshot
Dependabot PR #397
=> misc: improve node version (docker, module and cleanup modules)

src/app/explorer/dashboard/dashboard.component.html
Improve explorer button
From localhost
Before
After
No issue
=> misc: improve explorer button

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/farmer/farmer.component.html
Update values of pool/farmer block effort
Localhost
No screenshot
No issue
=> fix: update (pool & farmer) block effort

src/app/landing/landing.component.html, src/app/landing/landing.component.scss
Improve border of twitter card
From localhost
No screenshot
No issue
=> misc: improve radius of twitter card

package-lock.json
Modules upgrades
* From: 21 vulnerabilities (14 moderate, 7 high)
* To: 11 moderate severity vulnerabilities
From localhost, with pages navigation
No screenshot(s)
No issue(s)
=> misc: modules upgrades

package-lock.json, package.json
Merge jasmine module upgrades
From localhost
No screenshot
No issue
=> feat: merge jasmine

src/app/explorer/dashboard/dashboard.component.html, src/app/explorer/farmer/farmer.component.html
Fix Spacescan links (dashboard and farmer pages)
Online tests
No screenshot
No issue
=> fix: spacescan links

src/app/landing/landing.component.html, src/app/landing/landing.component.scss, src/app/landing/landing.component.ts, src/assets/scss/custom/_variables-dark.scss, src/assets/scss/custom/_variables.scss
Improve the landing page:
* Remove Twitter widget (not working and now useless)
* Rename Twitter badges to 𝕏 (and color updated)
* Improve texts format
From localhost
Issue #473
=> feat: global improvements

package-lock.json
Before:
```
18 vulnerabilities (14 moderate, 4 high)
```
After:
```
13 moderate severity vulnerabilities
```
=> feat: upgrade modules

src/app/explorer/login/login.component.html, src/app/explorer/login/login.component.ts
=> fix: custom difficulty
