openchia/web

- src/app/landing/landing.component.html
- src/assets/scss/custom/_card.scss
Fix top left radius on news section (landing page)
Before:
After:
> Fix top left radius on news section

- src/assets/scss/custom/_buttons.scss
Improve Discord social button in the footer.
Before:
After:
> Improve Discord social button color (footer)

- src/app/explorer/dashboard/dashboard.component.html
Before:
After:
⚠️ **Warning:** Don't look at the spacing, it's a test with `max-witdh: 1200px` from local
> Improve center text in explorer cases

- src/app/explorer/dashboard/dashboard.component.html
* Add farmer estimated space in explorer dashboard (TB)
* Align text center
Before:
After:
> Add estimated farmer space in explorer

- src/app/shared/navbar/navbar.component.html
* Fix language selection
Desktop (no major change):
Mobile (after touch current language):
> Fix language selector desktop/mobile (issue #20)

- package-lock.json
- package.json
- src/app/explorer/farmer/farmer.component.html
- src/app/explorer/farmer/farmer.component.ts
On farmer page and payouts tab:
* Total transactions
* Total payouts (XCH)
* Export payouts to CSV
Default view:
View when the farmer don't receive a payout (button disabled):
And a minor fixe when no payout:
> Add 'total transactions', 'total payouts' and export payouts to CSV

- src/app/explorer/farmer/farmer.component.html
Fix giveaway winner name in the farmer page
Here I use ngIf because by default giveaway.winner is null and not empty
> Fix winner name in giveaway farmer page

- src/app/landing/landing.component.ts
* Use PiB over TiB for pool space on the landing page (same value in the explorer page)
> Use pool size with PiB over TiB on the landing page

- src/app/explorer/farmer/farmer.component.html
* Use one column for title and split rewards per day/week/month (it's better)
> Improve farmer estimated reward

- src/app/explorer/farmer/farmer.component.html
* Invert "Joined At" and "Points"
* Add points pplns
* Show utilization space directly (same on dashboard)
> Improve farmer details

- src/app/explorer/farmer/farmer.component.html
- src/app/explorer/farmer/farmer.component.ts
Farmer page update (blocks tab):
* Show 100 blocks by default
* Rename from "Effort" to "Pool Effort"
* Move "Pool Effort" before "Pool Space" (pool section)
Yes from local
Yes, issue #199
> Update block effort on farmer page

- src/app/explorer/dashboard/dashboard.component.html
Improve block component in explorer page:
* `Effort` renamed to `Pool Effort` and moved after `Pool Space`
Local only
No
> Update block component

- src/app/explorer/farmer/farmer.component.css
- src/app/explorer/farmer/farmer.component.html
- src/app/explorer/farmer/farmer.component.ts
- src/app/stats/stats.component.html
- src/app/stats/stats.component.ts
- src/assets/scss/custom/_global.scss
Minor change(s):
* [farmer]: red line for partial error
* [farmer]: fix with table size
* [farmer]: add legend on estimated size
* [stats]: use area chart
* [stats]: chart colors updated
* [stats]: legend moved in bottom
From local (without docker)
Red line partial error:
Farmer estimated size:
Stats chart (new):
> Global improvements

- src/app/explorer/farmer/farmer.component.html
Add spacescan link on farmer and payout pages
From localhost
No
Issue #222
> Add spacescan links

- src/app/explorer/farmer/farmer.component.html
A note about HTML syntax (not related to declension): The `<br>` tag doesn't require a slash. The `/` in `<br/>` is redundant in  HTML, however it is required in XHTML.
See also: https://en.wikipedia.org/wiki/Slovak_declension
> Update farmer page translations for declension in Slavic languages

- src/app/join/join.component.html
- src/app/join/join.component.scss
- src/app/join/join.component.ts
Add copy clipboard function on join page
Only from localhost
Issue #239
> Add clipboard copy on join page

- src/app/stats/stats.component.ts
Improve space chart color in stats page
From localhost, with light and dark mode
Light mode:
Dark mode:
Issue #261
> Improve space chart colors

- src/app/explorer/payout/payout.component.html
- src/assets/scss/custom/_badge.scss
Improve payout page with a state of payment
From localhost, with light/dark mode
> Improve payout page when no transaction

- src/app/shared/navbar/navbar.component.html
- src/app/shared/navbar/navbar.component.scss
- src/app/shared/navbar/navbar.component.ts
Add a warning icon in the navbar if dust storm is true
From localhost, with light/dark mode. Call to /stats is checked and it's good 👍 
Issue #259
> Add a warning icon in the navbar if duststorm is true

- src/app/explorer/farmer/farmer.component.html
Added in farmer page:
* Client Version (Chia)
* Pool Connected
Details based on the last partial sent.
From localhost
> Add chia client version and pool connected

- package-lock.json
Update npm modules:
```
async  <2.6.4
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
fix available via `npm audit fix`
node_modules/async
moment  <2.29.2
Severity: high
Path Traversal: 'dir/../../filename' in moment.locale - https://github.com/advisories/GHSA-8hfj-j24r-96c4
fix available via `npm audit fix`
node_modules/moment
2 high severity vulnerabilities
```
Localhost only.
> Update npm modules (npm audit fix)

- src/app/explorer/farmer/farmer.component.css
- src/app/explorer/farmer/farmer.component.html
Improve farmer page:
* [fix] color of downloads button (payout tab) when dark mode is enabled
* [add] earned rewards with icons (based from estimated rewards)
Download button (before/after):
Earned rewards (light/dark mode):
* #302
* #297
> Improve farmer page (issue #302 and #297)

- src/app/explorer/farmer/farmer.component.html
Add icons in farmer page
From localhost
Loading:
Not found:
No
> Add icons (loading and not found) in farmer page

- src/app/explorer/dashboard/dashboard.component.html
- src/app/explorer/dashboard/dashboard.component.ts
- src/app/explorer/farmer/farmer.component.css
- src/app/explorer/farmer/farmer.component.ts
User persistent preferences:
* Farmer page, `Show failed partials only` button
* Explorer page, `Show active only` menu
From localhost (with/without cache), with manual changes, with reload, ...
No screenshot
* Issue #296
> User persistent preferences (issue #296)

- src/app/explorer/dashboard/dashboard.component.ts
Allow search farmer with full LauncherID, with/without `0x` 
No
Issue #317
> Allow full launcherid with/without '0x'

- src/app/explorer/farmer/farmer.component.html
- src/app/shared/navbar/navbar.component.html
- src/app/shared/navbar/navbar.component.ts
* Add how-to-login in navbar
* Replace light to secondary button
https://user-images.githubusercontent.com/2886596/221280972-0db4a2dd-bde5-4f85-9ebc-d0fa69770d5c.mp4
No issue
> feat: add how to login in navbar

- src/index.html
Set Safari tab colors, based from system preferences (light/dark mode)
Before:
After, light system and website:
Also dark system and website:
No issue
> feat: set safari tab colors (based from system preferences)

- src/app/explorer/dashboard/dashboard.component.css
- src/app/explorer/dashboard/dashboard.component.html
- src/assets/scss/custom/toggle-bootstrap-dark.scss
Improve view of pool effort in dashboard
Also badge colors for darkmode are general
> Between 80 and 120, it's orange
No issue
> feat: improve blocks luck view

- src/app/explorer/farmer/farmer.component.html
- src/app/explorer/farmer/farmer.component.ts
Add block luck average (blocks tab) in farmer page.
Average from the total blocks luck / total blocks.
No issue
> feat: add block luck average (block tab) in farmer page

- src/app/stats/stats.component.html
- src/app/stats/stats.component.ts
Improve block luck chart in stats page. Display per block because I prepare a new PR with per day view.
Yes localhost
No issue
> feat: improve stats luck chart (per block)

- angular-git-version.js
- src/app/shared/footer/footer.component.html
- src/app/shared/footer/footer.component.scss
Improve Github details in footer:
* Quick line to open an issue
* Details in table
* Date added
* Show tag if set, else it's the branch name
Small changes
No issue
> misc: improve github details in footer

- src/app/explorer/farmer/farmer.component.html
- src/app/explorer/farmer/farmer.component.ts
Reduce API calls in farmer page, now only when tab is selected (click).
Yes from localhost on each tab from zero
No screenshot (no visual changes)
Issue #234
> feat: reduce api callback in farmer page, load if tab is selected

- src/app/explorer/farmer/farmer.component.html
- src/app/explorer/farmer/farmer.component.ts
Add payouttxs chart (payouts tab) in the farmer page. Works with pagination.
> Need more tests for my part.
Yes from localhost, with big/small farmer (payouts)
Issue #347
> feat: add payouttxs chart in farmer page (payouts tab)

- src/app/explorer/farmer/farmer.component.ts
Fix payouttxs order (table) in farmer page
No screenshot
No issue
> fix: reverse payouttxs in farmer page

- src/app/explorer/login/login.component.css
- src/app/explorer/login/login.component.html
Fix farmer settings save button
No, only from live tests
Issue #356
> fix(farmer): settings save button

- src/app/explorer/login/login.component.css
- src/app/explorer/login/login.component.html
Add qrcode background (better view in darkmode)
No only live tests
Issue #357
> fix(farmer): settings qrcode background (darkmode)

- src/assets/scss/custom/toggle-bootstrap-dark.scss
Fix bottom white line in darkmode
Before:
After:
No issue
> fix: bottom white line in darkmode

- src/app/explorer/farmer/farmer.component.html
- src/app/explorer/farmer/farmer.component.ts
Improve payouttxs chart in farmer page:
* From line-area to bar chart (better view)
* Show unpaid payouttxs
No issue
> feat(farmer): move from line-area to bar chart for payouttxs

- src/app/explorer/farmer/farmer.component.html
Show blocks details only if a block has been won
Yes from localhost with a big and small farmers
Before:
After:
No issue
> fix: show farmer blocks details only if a blocks has been won

- src/app/explorer/farmer/farmer.component.ts
- src/assets/scss/custom/toggle-bootstrap-dark.scss
Fix farmer blocks view:
* Secondary badge text color
* Block effort when no data (return `-` and not `-1%`)
Issue #387
> fix(farmer): improve badge text color and effort

- src/app/explorer/farmer/farmer.component.ts
Improve view of estimated size (farmer page)
Before:
After:
No issue
> fix(farmer): estimated size chart values

- angular.json
- src/assets/scss/custom/toggle-bootstrap-dark.scss
- src/assets/scss/custom/toggle-bootstrap.scss
Warnings fixes during `npm run start` command:
* 5 warnings related to dependencies (`CommonJS or AMD dependencies can cause optimization bailouts`)
* 2 warnings related to bootstrap pseudo class lang
No screenshot
No issue
> fix(cli): npm run start warning

- src/app/explorer/farmer/farmer.component.html
- src/app/explorer/farmer/farmer.component.ts
Fix the farmer effort average method of calcul. Not based from all blocks (require a new call without limit).
So now effort average is based on blocks in the list (works with pagination).
From localhost
No screenshot.
No issue opened. This bug has been reported on Discord.
> fix(farmer): blocks effort average

- src/app/explorer/farmer/farmer.component.html
- src/app/explorer/farmer/farmer.component.ts
Allow to export the list of blocks (farmer) in CSV format
From localhost
> Empty case when xch price is not defined
> Effort -1 when is not defined
Issue #416
> feat: add blocks csv export

- README.md
- src/app/giveaway/giveaway.component.html
- src/app/landing/landing.component.html
- src/app/landing/landing.component.ts
- src/app/shared/footer/footer.component.html
- src/app/shared/navbar/navbar.component.html
- src/assets/scss/custom/_buttons.scss
- src/locale/en.xlf
* Remove OpenChia Twitter widget
* Replaced by Discord widget
* Improve Discord button color (aligned with the widget)
* Call widget in good mode (dark/light)
From localhost
Dark mode:
Light mode:
Issue #429
> feat: remove openchia twitter
